# Generated by Django 4.2 on 2025-02-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "product_model",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Модель продукта",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="дата выхода продукта на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название организации",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Введите страну",
                        max_length=35,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Введите город",
                        max_length=35,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Введите улицу",
                        max_length=35,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Введите номер дома",
                        max_length=35,
                        null=True,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Введите задолженность с точностью до копеек",
                        max_digits=15,
                        max_length=35,
                        verbose_name="Задолженность",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Завод", "Завод"),
                            ("Розничная сеть", "Розничная сеть"),
                            (
                                "Индивидуальный предприниматель",
                                "Индивидуальный предприниматель",
                            ),
                        ],
                        max_length=150,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(to="sales.product", verbose_name="Продукты"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.organization",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "организация",
                "verbose_name_plural": "организации",
            },
        ),
    ]
